### ISSUE TITLE
Indirect bookmark jump breaks tab-bar-mode

### ISSUE THREAD

**Issue by SterlingHooten** [alphapapa/org-bookmark-heading#15]
Calling bookmark jump to open an org heading in an indirect buffer produces a state that causes tab-bar-mode to throw error `Wrong type argument: listp, #<buffer 1.org<org>>` and cease working in that frame. Opening up a new frame restores functionality, but jumping to the heading again will produce the same issues.

I was able to recreate this with emacs -q and the following setup:
```
(load "path/to/org-bookmark-heading.el")
(require 'org-bookmark-heading)
(tab-bar-mode 1)
(setq org-bookmark-jump-indirect t)
; Bookmark "alpha heading" with org-id property in file 1.org
(tab-new) ; Create a new tab, works fine
(bookmark-bmenu-list) ; select "alpha heading" to jump to indirectly
(tab-new) ; Create a new tab, now gives error:
; Error mapcar: Wrong type argument: listp, #<buffer 1.org<org>>

;; Error doesn't persist in new frame:
(make-frame-command)
(tab-new) ;Create a new tab, works fine

;; But can be generated again:
(bookmark-bmenu-list) ; select "alpha heading" to jump to indirectly
(tab-new) ; Create a new tab, now gives error:
; Error mapcar: Wrong type argument: listp, #<buffer 1.org<org>>
```
I don't know if this is killing the base buffer, or where things are exactly going wrong in the setup.

As an aside, it might be worthwhile to avoid using `org-id-goto` as it disturbs the existing point or state of the base buffer. This is annoying when the bookmark is pulling up a heading in a buffer where you're already working, and then org-bookmark-heading moves the point around. Ideally jumping to an indirect bookmark should be free of buffer-state side-effects.

```
;; Stock function
(defun org-id-goto (id)
  "Switch to the buffer containing the entry with id ID.
Move the cursor to that entry in that buffer."
  (interactive "sID: ")
  (let ((m (org-id-find id 'marker)))
    (unless m
      (error "Cannot find entry with ID \"%s\"" id))
    (pop-to-buffer-same-window (marker-buffer m))
    (goto-char m)
    (move-marker m nil)
    (org-show-context)))
```

Here's a stripped down version I've been using that avoids altering the state of the base buffer.

```
(defun org-id-goto-indirect (id)
  "Open subtree of entry with id ID in an Indirect buffer.
Move the cursor to that entry in that buffer."
  (interactive "sID: ")
  (let ((m (org-id-find id 'marker)))
    (unless m
      (error "Cannot find entry with ID \"%s\"" id))
    (with-current-buffer (marker-buffer m)
      (save-excursion
	(goto-char m)
    ;; Point marker nowhere so it won't slow down editing buffer
	(move-marker m nil)
	(org-tree-to-indirect-buffer)))))
```

**Comment by alphapapa** [comment]
Hi Sterling,

The commit I just pushed seems to fix this problem.  Please let me know how it works for you.

And thank you very much for reporting this and investigating it.  I'd been seeing this problem in my own config lately, but I didn't realize it was caused by changes I had made in this package, so I was barking up the wrong tree.  You saved me a lot of grief!

**Comment by alphapapa** [comment]
By the way:

> As an aside, it might be worthwhile to avoid using `org-id-goto` as it disturbs the existing point or state of the base buffer. This is annoying when the bookmark is pulling up a heading in a buffer where you're already working, and then org-bookmark-heading moves the point around. Ideally jumping to an indirect bookmark should be free of buffer-state side-effects.

`org-id-goto` isn't called by `org-bookmark-heading`, so I'm not sure where you're finding that.  But the point about not moving point in the base buffer is good.  Feel free to open another issue about that and we can talk about solving it.

**Comment by SterlingHooten** [comment]
Just tried out the new version, appears to be fixed, thanks for the fast patch!
