### ISSUE TITLE
Filtering Org bookmarks in the *Bookmark List* buffer with bookmark-plus

### ISSUE THREAD

**Issue by jmay** [alphapapa/org-bookmark-heading#20]
The `bookmark+` package has a [filtering feature](https://www.emacswiki.org/emacs/BookmarkPlus#h5o-52) for the bookmarks list.

Does this package add a filter option for Org bookmarks? Org bookmarks don't appear when any of the other filters are activated. Perhaps this should be a feature request ... would that belong here or on bookmark+?

**Comment by jmay** [comment]
Wow, the `bookmark-plus` code is ugly. https://github.com/emacsmirror/bookmark-plus

"Created: Fri Sep 15 07:58:41 2000", with 60+ "features that might be required by this library". Yikes. I'd rather not touch that codebase.

I propose to contribute a change here, using `with-eval-after-load` in the same way you've done for `helm-bookmark`.

**Comment by alphapapa** [comment]
As you noticed, that library (which is actually maintained on Emacswiki, by the way) has a long history and many, many features in its code.  While I appreciate it for what it is, as I said on the PR, I don't think it would be appropriate to support it in this package directly.

To not let your PR's code go to waste, we could, e.g. add it to a wiki on this repo so users could add it to their configs.

**Comment by jmay** [comment]
That's a good idea. I'd like to save others from having to repeat the chore of delving into the Bookmark+ code, so having some reference code available here would be a good idea. If you add a Wiki page to this repo then I'll paste in my linking code.

**Comment by alphapapa** [comment]
@jmay Thanks for your patience.  I added a spot for you to add your code here: https://github.com/alphapapa/org-bookmark-heading/wiki#bookmarks
