### ISSUE TITLE
Handle archived subtrees

### ISSUE THREAD

**Issue by martintrojer** [alphapapa/org-bookmark-heading#5]
Would be really nice if bookmarks keeps working after subtrees have been archived.

I.e. after `M-x org-archive-subtree`

**Comment by alphapapa** [comment]
I guess you'd have to configure Org to search archive files when searching for IDs.  I don't know if that's already possible.

**Comment by martintrojer** [comment]
I just tried this again and it already works. Unclear what me previous problem was :-)

Sorry for the noise.
