### ISSUE TITLE
How to stop automatic creation of org ids during capture and refiling

### ISSUE THREAD

**Issue by krvpal** [alphapapa/org-bookmark-heading#8]
Hi, thanks a lot for this excellent package. I agree with the other comments that this must be included as part of mainline Org.

I'm having issues in trying to stop org-ids being automatically created during normal refiling or capturing actions. It's a bit excessive as I usually refile a lot of headings and capture even more on a daily basis, and it's totally unnecessary to have ids for every heading. This also increases the size of 'org-id-locations-file'.

I'm aware this is due to Org's functionality of creating automatic bookmarks during refiling or capturing. I managed to set `org-capture-bookmark` to nil which helped a bit, but I see there is no easy way to stop this behavior during refiling functions. I also noticed in your code some references to a workaround for this problem, but it seems not to work in my case at all.

I'd be grateful for any suggestions to get around this.

**Comment by alphapapa** [comment]
Hi, thanks, I'm glad it's useful to you.

I guess the best solution would be for Org to have an option to disable the making of bookmarks when refiling.  You could propose that as a patch to Org.

Alternatively, you could use function advice in your config to prevent the bookmarks from being made.  Maybe you'd just need to call the same function but with a variable bound differently.

**Comment by wuqui** [comment]
I have the exact same issues with this! And it's really annoying. The kind of refiling I want to do becomes basically impossible because it would clutter files with IDs way too much.

Could anyone help with the "function advice" maybe? I don't have the elisp skills, unfortunately.

**Comment by krvpal** [comment]
This is more than a year late, but I did manage to find an easier solution. The variable in question that decides if bookmarks are created while refiling or capturing is `org-bookmark-names-plist`. 

The simplest solution is to completely disable these automatic bookmarks that org creates by adding the following:
`(setq org-bookmark-names-plist nil)`

You could also selectively control which automated bookmarks to disable. Here's the description for this variable in Org:
```
Names for bookmarks automatically set by some Org commands.

This can provide strings as names for a number of bookmarks Org sets
automatically.  The following keys are currently implemented:
  :last-capture
  :last-capture-marker
  :last-refile
When a key does not show up in the property list, the corresponding bookmark
is not set.
```

@alphapapa - maybe this could be added to the project's docs if you think it might help others? Thanks again for this really helpful package.

**Comment by alphapapa** [comment]
> @alphapapa - maybe this could be added to the project's docs if you think it might help others? Thanks again for this really helpful package.

Yes, that's a good idea.  Thanks.

**Comment by alphapapa** [comment]
I think this should have been fixed by https://github.com/alphapapa/org-bookmark-heading/commit/7fa7cc1bd012fade0899a0a26fb8353f3c8839ac.  I'm not sure it's necessary to add to the documentation, especially since it defaults to nil.  Feel free to say something if you disagree.  :)
